[pytest]
addopts = -s --alluredir=allure-results
log_cli = 1
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format=%Y-%m-%d %H:%M:%S
pythonpath = .

markers =
    accesscontrol: проверка доступов
    regression: регресс-тесты
    validation: тесты на валидацию
    movies: тестируем MoviesAPI
    smoke.mock: проверяем, что моки поднялись и отвечают
    smoke: проверяем, что апи подняты и отвечают
    edgecases: edge-кейсы
    

